name: Download Terraform

on: [push]

jobs:
  download-terraform:
    runs-on:
      - self-hosted
      - lab
    env:
      TERRAFORM_SETUP_LOG_PATH: /tmp/terraform-setup.log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform setup
        run: |
          sudo chmod +x ./terraform-setup.sh
          sudo ./terraform-setup.sh $TERRAFORM_SETUP_LOG_PATH
        continue-on-error: true

      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-install-log
          path: $TERRAFORM_SETUP_LOG_PATH
