name: Download Terraform

on: [push]

jobs:
  download-terraform:
    runs-on:
      - self-hosted
      - lab

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute download_terraform.sh script
        run: |
          sudo chmod +x ./download_terraform.sh
          sudo ./download_terraform.sh
        continue-on-error: true

      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-install-log
          path: /tmp/terraform_install.log
