name: Test Terraform setup script
run-name: ${{ github.actor }} is running ${{ github.workflow }} (run ${{ github.run_number }})

on:
  push:
    branches:
      - main

jobs:
  download-terraform:
    runs-on: ubuntu-latest
    env:
      TERRAFORM_SETUP_LOG_PATH: ~/terraform-setup.log

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Terraform setup
        run: |
          sudo chmod +x ./terraform-setup.sh
          sudo ./terraform-setup.sh $TERRAFORM_SETUP_LOG_PATH
        continue-on-error: true

      - name: Upload log file on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-install-log
          path: $TERRAFORM_SETUP_LOG_PATH

  create-release:
    runs-on: ubuntu-latest
    needs: download-terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            Release notes for terraform-setup.sh

      - name: Upload terraform-setup.sh to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./terraform-setup.sh
          asset_name: terraform-setup.sh
          asset_content_type: application/x-sh
